### PR TITLE
Jim modify

### PR DESCRIPTION
**Pull request by jsitu777**
Jim modify for MPK 22 batch export MEP revit models into nwc

### CODE REVIEW

**Comment by wsituGT** [comment]
modify to export MPK 22 MEP files to dated nwc

**Review by jchristel — CHANGES_REQUESTED** [review]
Hi Jim,

Thank you very much for providing pull requests for Batch processor sample scripts.

Please note though that a majority of your changes appear to be company / project specific i.e. file path locations

I'm trying to keep these samples as generic as possible hence I'm just pointing at C:\temp even though in my real life working code I'm not using that location at all.

Can you please review your pull requests and only submit changes which are:
- bug fixes 
- improvements in terms of functionality.

Kind Regards,

Jan

**Comment by jsitu777** [comment]
Hi Jan,

Thanks for your reply. This was a mistake, I have now closed the pull request.

**Comment by jchristel** [comment]
Thanks Jim

**Pull request closed without merging**
